# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false
r_build_args: '--compact-vignettes="gs+qpdf"'
r_packages:
  - covr
  - data.table
  - ape
  - phytools
  - quadprog
  - igraph
after_success:
  - Rscript -e 'covr::codecov()'

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:cran/imagemagick'
    packages:
      - libmagick++-dev
